baseURL = "https://ressona.eu/"
title = "Ressona"
defaultContentLanguage = "ca"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[params]
  description = "Identitat digital per a artistes"
  author = "Ressona"
  instagram = "https://www.instagram.com/ressona.eu/"
  email = "hola@ressona.eu"
  logo = "/img/ressona-logo.svg"
  mark = "/img/ressona-mark.svg"
  goatcounter = "ressona"

[languages]
  [languages.ca]
    languageName = "Català"
    contentDir = "content"
    weight = 1
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true

[build]
  writeStats = false
