baseURL = "https://ressona.eu/"
title = "Ressona"
defaultContentLanguage = "ca"
disableKinds = ["RSS"]
enableRobotsTXT = true

[params]
  description = "Identitat digital per a artistes"
  author = "Ressona"
  instagram = "https://www.instagram.com/ressona_identitat_digital/"
  email = "hola@ressona.eu"
  logo = "/img/ressona-logo.svg"
  mark = "/img/ressona-mark.svg"
  goatcounter = "ressona"

[languages]
  [languages.ca]
    languageName = "Català"
    contentDir = "content"
    weight = 1
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"

[outputs]
  home     = ["HTML", "JSON"]
  section  = ["HTML", "JSON"]
  taxonomy = ["HTML"]
  term     = ["HTML"]

[build]
  writeStats = false
